# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    
    config.vm.hostname = "kafka.example.com"
    config.vm.network "private_network", ip: "192.168.56.8"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "kafka"
      vb.memory = "2048"
      vb.cpus = 2
    end
end