# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    
    config.vm.hostname = "slave.example.com"
    config.vm.network "private_network", ip: "192.168.56.11"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "slave"
      vb.memory = "4096"
      vb.cpus = 2
    end
end