# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    
    config.vm.hostname = "client.example.com"
    config.vm.network "private_network", ip: "192.168.56.12"
    config.vm.provider "virtualbox" do |vb|
    vb.name = "client"
    vb.memory = "2048"
    vb.cpus = 1
    end
end