# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    
    config.vm.hostname = "kerberos.example.com"
    config.vm.network "private_network", ip: "192.168.56.9"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "kerberos"
      vb.memory = "1024"
      vb.cpus = 2
    end
end