---
# Creating the global variables for all the containers
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
  KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:29093'
  KAFKA_PROCESS_ROLES: "broker,controller"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
  KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
  CLUSTER_ID: "ciWo7IWazngRchmPES6q5A=="

---
# Creating the  kafka containers within a pod
apiVersion: v1
kind: Pod
metadata:
  name: kafka-pod
  labels:
    app: kafka-pod
spec:
  containers:
    - name: kafka1
      image: confluentinc/cp-kafka
      ports:
        - containerPort: 9092
        - containerPort: 29093
      envFrom:
        - configMapRef:
            name: kafka-config
      env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_LISTENERS
          value: "INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://localhost:9092"

    - name: ssh
      image: weas/ubuntu-kafka
---
# Create service to reach the kafka containers in the pod
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
    - name: ssh-port
      port: 5022
      targetPort: 22
  selector:
    app: kafka-pod
